// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBqWIORUWPhr00lB9UAs2TuskUeH9gTKg',
    appId: '1:1030894685563:web:1b5585b66926d2dd2581de',
    messagingSenderId: '1030894685563',
    projectId: 'chatbox-db8ca',
    authDomain: 'chatbox-db8ca.firebaseapp.com',
    storageBucket: 'chatbox-db8ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkYwhOSGpneqkrLlxG1ZvJEi0DCP0A7bc',
    appId: '1:1030894685563:android:82c34ebc081eb0722581de',
    messagingSenderId: '1030894685563',
    projectId: 'chatbox-db8ca',
    storageBucket: 'chatbox-db8ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLveBsM9vBfKC1ZA1Dww3hlYcJocaRlso',
    appId: '1:1030894685563:ios:59e8ee8edc92a6c52581de',
    messagingSenderId: '1030894685563',
    projectId: 'chatbox-db8ca',
    storageBucket: 'chatbox-db8ca.appspot.com',
    iosBundleId: 'com.example.chatbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLveBsM9vBfKC1ZA1Dww3hlYcJocaRlso',
    appId: '1:1030894685563:ios:a44128e9a89d9f642581de',
    messagingSenderId: '1030894685563',
    projectId: 'chatbox-db8ca',
    storageBucket: 'chatbox-db8ca.appspot.com',
    iosBundleId: 'com.example.chatbox.RunnerTests',
  );
}
